#!/bin/bash 

# path tor config file 
tor_config_file="/etc/tor/torrc"

# url get bridge
url_bridges="https://bridges.torproject.org/bridges?transport=obfs4"

# for manage uninstall 
file_projects="get-tor-bridges bridges-manager tbcli-config"
path=$(which "get-tor-bridges" |sed 's/[^\/]*$//g')

# colors 
nc="\e[0m"
black="\e[30m"
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
light_gray="\e[37m"
dark_gray="\e[90m"
light_red="\e[91m"
light_green="\e[92m"
light_yellow="\e[93m"
light_blue="\e[94m"
light_magenta="\e[95m"
light_cyan="\e[96m"
white="\e[97m"