#!/bin/bash 

# path tor config file 
tor_config_file="/etc/tor/torrc"

# url get bridge
url_bridges="https://bridges.torproject.org/bridges?transport=obfs4"

# change variables if you dont use systemd deamon manager  
tor_restart="systemctl restart tor.service"
tor_status="systemctl status tor.service"
####
# if u cant see log tor with systemctl status tor.service 
#### install : 
# sudo apt install apparmor-utils
# sudo aa-complain system_tor
#### then use this variable 
# tor_status="sudo systemctl status tor@default.service"
# temp files 
HTML_FILE="img.html"
IMAGE_CAPTCHA_FILE="captcha.jpg"
BridgeFile="bridges.txt"

# my ip 
IpSite="icanhazip.com"

# colors 
nc="\e[0m"
black="\e[30m"
red="\e[31m"
green="\e[32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
light_gray="\e[37m"
dark_gray="\e[90m"
light_red="\e[91m"
light_green="\e[92m"
light_yellow="\e[93m"
light_blue="\e[94m"
light_magenta="\e[95m"
light_cyan="\e[96m"
white="\e[97m"

# tor reset separator
reset_sep="${light_red} >${light_blue}%"
